<p style="align: center;"><img src="https://static.tildacdn.com/tild6636-3531-4239-b465-376364646465/Deep_Learning_School.png", width=300, height=300></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

<h2 style="text-align: center;"><b>Python. Домашнее задание: Основы Python, Numpy, Scipy</b></h2>

In [1]:
import numpy as np

from scipy.stats import uniform
from scipy.optimize import fmin

### Основы Python

### Задача 0

На самом деле тут несколько задач: нужно прорешать все задачи в ноутбуке с первой лекции ([python][1]basics.ipynb).  
Тот ноутбук послать в письме с домашкой (вместе с этим ноутбуком).  
Итого у вас в письме с домашкой будет 2 файла с расширением .ipynb (решённый ноутбук с 1-ой лекции и этот ноутбук).  

*Примечание:* Для того, чтобы сделать задачу, связанную с чтением файлов (6-ая задача), нужно скачать материалы (всю папку [lesson1]basics) в гугл-диске с материалами. Ссылка на гугл-диск: https://drive.google.com/drive/u/0/folders/14XCkhcvXmT4cs4mOy10MD1hcFpZo8sNV (python -> [lesson1]basics -> скачать всю папку, материалы там)

# Numpy

### Задача 1.1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
A = np.random.sample((177, 111))
B = np.random.sample((111, 100))

print('dim A = {}\ndim B = {}\n'.format(A.ndim, B.ndim))

print('Shape of A is: {}'.format(A.shape))
print('Shape of B is: {}\n'.format(B.shape))

print('\tMatrix A\n{}\n'.format(A[:3, :3]))
print('\tMatrix B\n{}\n'.format(B[:3, :3]))

dim A = 2
dim B = 2

Shape of A is: (177, 111)
Shape of B is: (111, 100)

	Matrix A
[[0.16938695 0.82647705 0.08977421]
 [0.16322034 0.00720073 0.7775328 ]
 [0.37688763 0.51960273 0.14742066]]

	Matrix B
[[0.68040163 0.07203523 0.75860295]
 [0.55007838 0.89306785 0.48320618]
 [0.72369493 0.55472736 0.23122649]]



In [3]:
def mult(A, B):
    C = [([0] * B.shape[1]) for i in range(A.shape[0])]
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            acc = 0
            for k in range(A.shape[1]):
                acc += A[i][k] * B[k][j]
            C[i][j] = acc
    return C

In [4]:
def np_mult(A, B):
    return np.dot(A, B)

In [5]:
%%time
tmp = mult(A, B)

CPU times: user 1.08 s, sys: 11.3 ms, total: 1.1 s
Wall time: 1.11 s


In [6]:
%%time
tmp = np_mult(A, B)

CPU times: user 885 µs, sys: 298 µs, total: 1.18 ms
Wall time: 716 µs


### Задача 1.2

Умножить матрицы вручную и в Numpy. Сверить результат, убедиться, что всё совпало:

In [7]:
A = np.array([[10, 5, -4], [12, 1, -14]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

slow = mult(A, B)
fast = np_mult(A, B)

print('\tAre results the same?\n{}'.format(slow == fast))

	Are results the same?
[[ True  True  True]
 [ True  True  True]]


### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [8]:
def sequence(A):
    S = [0] * (len(A))
    acc = 0
    for k in range(1, len(A) + 1):
        acc += A[k - 1]
        S[k - 1] = acc / k
    return S

In [9]:
def np_sequence(A):
    return np.cumsum(A) / np.arange(1, len(A) + 1)

In [10]:
A = uniform.rvs(size=10 ** 7) 

%time S1 = sequence(A)
%time S2 = np_sequence(A)

print('\nDifference: {}'.format(np.abs(S1 - S2).sum()))

CPU times: user 4.77 s, sys: 103 ms, total: 4.88 s
Wall time: 4.9 s
CPU times: user 78.7 ms, sys: 41.3 ms, total: 120 ms
Wall time: 120 ms

Difference: 0.0


### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X ("склеить горизонтально") и вывести в обратном порядке результат.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [11]:
def transformation(X, a = 1):
    tmp = [0] * len(X)
    for i in range(len(X)):
        if i % 2 == 0:
            if len(X) % 2 == 0:
                tmp[len(X) - i - 2] = X[i] ** 3
            else:
                tmp[len(X) - i - 1] = X[i] ** 3
        else:
            tmp[i] = a

    Y = [0] * 2 * len(X)
    for i in range(len(Y)):
        if i < len(X):
            Y[i] = X[i]
        else:
            Y[i] = tmp[i - len(X)]

    return Y

In [12]:
def np_transformation(X, a = 1):
    Y = np.copy(X)
    Y[1::2] = a
    Y[::2] = (Y[::2] ** 3)[::-1]
    return np.hstack((X, Y))

In [13]:
X = np.array([1, 2, 3, 4, 5])

Q = np_transformation(X)
T = transformation(X)

print('\tQ\n{}'.format(Q))
print('\tT\n{}'.format(T))

	Q
[  1   2   3   4   5 125   1  27   1   1]
	T
[1, 2, 3, 4, 5, 125, 1, 27, 1, 1]


In [14]:
X = uniform.rvs(size=10**7) 

%time S1 = transformation(X)
%time S2 = np_transformation(X)

print('\nDifference: {}'.format(np.abs(S1 - S2).sum()))

CPU times: user 8.85 s, sys: 264 ms, total: 9.11 s
Wall time: 9.19 s
CPU times: user 183 ms, sys: 67.6 ms, total: 250 ms
Wall time: 250 ms

Difference: 0.0


# SciPy

### Задача 4.1

Дана функция f(), Вам нужно найти её **максимум** с помощью библиотеки scipy.

In [15]:
def f(x):
    return -5 * x ** 2 + 9 * x - 2 

In [16]:
tmp = fmin(lambda x: -f(x), 0)

Optimization terminated successfully.
         Current function value: -2.050000
         Iterations: 25
         Function evaluations: 50


### Задача 4.2

Оптимизируйте (найди минимум и точку минимума) функции двух переменных:

In [17]:
def f(x):
    return (x[0] + 2 * x[1] - 7) ** 2 + (2 * x[0] + x[1] - 5) ** 2

In [18]:
point = fmin(f, np.array((0, 0)))
print('Point of minimum:\nx[0] = {}\tx[1] = {}'.format(point[0], point[1]))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 67
         Function evaluations: 132
Point of minimum:
x[0] = 1.000018462214465	x[1] = 2.9999657858162263
